/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    pillars: Pillar;
    services: Service;
    projects: Project;
    posts: Post;
    'team-members': TeamMember;
    testimonials: Testimonial;
    'pricing-packages': PricingPackage;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    pillars: PillarsSelect<false> | PillarsSelect<true>;
    services: ServicesSelect<false> | ServicesSelect<true>;
    projects: ProjectsSelect<false> | ProjectsSelect<true>;
    posts: PostsSelect<false> | PostsSelect<true>;
    'team-members': TeamMembersSelect<false> | TeamMembersSelect<true>;
    testimonials: TestimonialsSelect<false> | TestimonialsSelect<true>;
    'pricing-packages': PricingPackagesSelect<false> | PricingPackagesSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'site-settings': SiteSetting;
    homepage: Homepage;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    homepage: HomepageSelect<false> | HomepageSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumb?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    hero?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pillars".
 */
export interface Pillar {
  id: number;
  title: string;
  slug: string;
  icon?: (number | null) | Media;
  shortDescription?: string | null;
  positioningStatement?: string | null;
  heroImage?: (number | null) | Media;
  heroPrimaryCta?: {
    label?: string | null;
    href?: string | null;
  };
  heroSecondaryCta?: {
    label?: string | null;
    href?: string | null;
  };
  introduction?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  whyItMatters?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  differentiators?:
    | {
        title?: string | null;
        description?: string | null;
        id?: string | null;
      }[]
    | null;
  process?:
    | {
        title?: string | null;
        description?: string | null;
        id?: string | null;
      }[]
    | null;
  faqs?:
    | {
        question: string;
        answer: string;
        id?: string | null;
      }[]
    | null;
  order?: number | null;
  services?: (number | Service)[] | null;
  caseStudies?: (number | Project)[] | null;
  testimonial?: (number | null) | Testimonial;
  seo?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
    ogTitle?: string | null;
    ogDescription?: string | null;
    ogImage?: (number | null) | Media;
    canonicalUrl?: string | null;
    noIndex?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services".
 */
export interface Service {
  id: number;
  title: string;
  slug: string;
  shortDescription?: string | null;
  heroImage?: (number | null) | Media;
  heroPrimaryCta?: {
    label?: string | null;
    href?: string | null;
  };
  heroSecondaryCta?: {
    label?: string | null;
    href?: string | null;
  };
  whatIncluded?:
    | {
        item?: string | null;
        id?: string | null;
      }[]
    | null;
  techStack?:
    | {
        tool?: string | null;
        id?: string | null;
      }[]
    | null;
  process?:
    | {
        title?: string | null;
        description?: string | null;
        id?: string | null;
      }[]
    | null;
  pricingStartingFrom?: string | null;
  featureBlocks?:
    | {
        heading?: string | null;
        body?: string | null;
        image?: (number | null) | Media;
        id?: string | null;
      }[]
    | null;
  faqs?:
    | {
        question: string;
        answer: string;
        id?: string | null;
      }[]
    | null;
  pillar: number | Pillar;
  caseStudies?: (number | Project)[] | null;
  relatedServices?: (number | Service)[] | null;
  seo?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
    ogTitle?: string | null;
    ogDescription?: string | null;
    ogImage?: (number | null) | Media;
    canonicalUrl?: string | null;
    noIndex?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects".
 */
export interface Project {
  id: number;
  title: string;
  slug: string;
  client?: string | null;
  industry?: string | null;
  platformTags?:
    | {
        tag?: string | null;
        id?: string | null;
      }[]
    | null;
  coverImage?: (number | null) | Media;
  gallery?:
    | {
        image: number | Media;
        id?: string | null;
      }[]
    | null;
  challenge?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  strategy?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  solution?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  results?:
    | {
        value?: string | null;
        label?: string | null;
        id?: string | null;
      }[]
    | null;
  featured?: boolean | null;
  timeline?: string | null;
  pillars?: (number | Pillar)[] | null;
  services?: (number | Service)[] | null;
  testimonial?: (number | null) | Testimonial;
  seo?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
    ogTitle?: string | null;
    ogDescription?: string | null;
    ogImage?: (number | null) | Media;
    canonicalUrl?: string | null;
    noIndex?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials".
 */
export interface Testimonial {
  id: number;
  quote: string;
  authorName?: string | null;
  authorRole?: string | null;
  company?: string | null;
  avatar?: (number | null) | Media;
  relatedProject?: (number | null) | Project;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: number;
  title: string;
  slug: string;
  excerpt?: string | null;
  coverImage?: (number | null) | Media;
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Blog categories map to the 4 service pillars.
   */
  category?: (number | null) | Pillar;
  author?: (number | null) | TeamMember;
  publishedAt?: string | null;
  updatedAt: string;
  seo?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
    ogTitle?: string | null;
    ogDescription?: string | null;
    ogImage?: (number | null) | Media;
    canonicalUrl?: string | null;
    noIndex?: boolean | null;
  };
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "team-members".
 */
export interface TeamMember {
  id: number;
  name: string;
  slug: string;
  role?: string | null;
  photo?: (number | null) | Media;
  bio?: string | null;
  skillTags?:
    | {
        tag?: string | null;
        id?: string | null;
      }[]
    | null;
  linkedin?: string | null;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pricing-packages".
 */
export interface PricingPackage {
  id: number;
  name: string;
  description?: string | null;
  /**
   * e.g. 'LKR 250,000' or 'Custom'
   */
  price?: string | null;
  /**
   * e.g. 'one-time' or 'per month'
   */
  billingNote?: string | null;
  features?:
    | {
        feature?: string | null;
        id?: string | null;
      }[]
    | null;
  highlighted?: boolean | null;
  cta?: {
    label?: string | null;
    href?: string | null;
  };
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'pillars';
        value: number | Pillar;
      } | null)
    | ({
        relationTo: 'services';
        value: number | Service;
      } | null)
    | ({
        relationTo: 'projects';
        value: number | Project;
      } | null)
    | ({
        relationTo: 'posts';
        value: number | Post;
      } | null)
    | ({
        relationTo: 'team-members';
        value: number | TeamMember;
      } | null)
    | ({
        relationTo: 'testimonials';
        value: number | Testimonial;
      } | null)
    | ({
        relationTo: 'pricing-packages';
        value: number | PricingPackage;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumb?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        hero?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pillars_select".
 */
export interface PillarsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  icon?: T;
  shortDescription?: T;
  positioningStatement?: T;
  heroImage?: T;
  heroPrimaryCta?:
    | T
    | {
        label?: T;
        href?: T;
      };
  heroSecondaryCta?:
    | T
    | {
        label?: T;
        href?: T;
      };
  introduction?: T;
  whyItMatters?: T;
  differentiators?:
    | T
    | {
        title?: T;
        description?: T;
        id?: T;
      };
  process?:
    | T
    | {
        title?: T;
        description?: T;
        id?: T;
      };
  faqs?:
    | T
    | {
        question?: T;
        answer?: T;
        id?: T;
      };
  order?: T;
  services?: T;
  caseStudies?: T;
  testimonial?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        ogTitle?: T;
        ogDescription?: T;
        ogImage?: T;
        canonicalUrl?: T;
        noIndex?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services_select".
 */
export interface ServicesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  shortDescription?: T;
  heroImage?: T;
  heroPrimaryCta?:
    | T
    | {
        label?: T;
        href?: T;
      };
  heroSecondaryCta?:
    | T
    | {
        label?: T;
        href?: T;
      };
  whatIncluded?:
    | T
    | {
        item?: T;
        id?: T;
      };
  techStack?:
    | T
    | {
        tool?: T;
        id?: T;
      };
  process?:
    | T
    | {
        title?: T;
        description?: T;
        id?: T;
      };
  pricingStartingFrom?: T;
  featureBlocks?:
    | T
    | {
        heading?: T;
        body?: T;
        image?: T;
        id?: T;
      };
  faqs?:
    | T
    | {
        question?: T;
        answer?: T;
        id?: T;
      };
  pillar?: T;
  caseStudies?: T;
  relatedServices?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        ogTitle?: T;
        ogDescription?: T;
        ogImage?: T;
        canonicalUrl?: T;
        noIndex?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects_select".
 */
export interface ProjectsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  client?: T;
  industry?: T;
  platformTags?:
    | T
    | {
        tag?: T;
        id?: T;
      };
  coverImage?: T;
  gallery?:
    | T
    | {
        image?: T;
        id?: T;
      };
  challenge?: T;
  strategy?: T;
  solution?: T;
  results?:
    | T
    | {
        value?: T;
        label?: T;
        id?: T;
      };
  featured?: T;
  timeline?: T;
  pillars?: T;
  services?: T;
  testimonial?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        ogTitle?: T;
        ogDescription?: T;
        ogImage?: T;
        canonicalUrl?: T;
        noIndex?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  excerpt?: T;
  coverImage?: T;
  body?: T;
  category?: T;
  author?: T;
  publishedAt?: T;
  updatedAt?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        ogTitle?: T;
        ogDescription?: T;
        ogImage?: T;
        canonicalUrl?: T;
        noIndex?: T;
      };
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "team-members_select".
 */
export interface TeamMembersSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  role?: T;
  photo?: T;
  bio?: T;
  skillTags?:
    | T
    | {
        tag?: T;
        id?: T;
      };
  linkedin?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials_select".
 */
export interface TestimonialsSelect<T extends boolean = true> {
  quote?: T;
  authorName?: T;
  authorRole?: T;
  company?: T;
  avatar?: T;
  relatedProject?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pricing-packages_select".
 */
export interface PricingPackagesSelect<T extends boolean = true> {
  name?: T;
  description?: T;
  price?: T;
  billingNote?: T;
  features?:
    | T
    | {
        feature?: T;
        id?: T;
      };
  highlighted?: T;
  cta?:
    | T
    | {
        label?: T;
        href?: T;
      };
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  siteName?: string | null;
  tagline?: string | null;
  logo?: (number | null) | Media;
  contact?: {
    email?: string | null;
    phone?: string | null;
    address?: string | null;
  };
  socialLinks?:
    | {
        platform?: ('Facebook' | 'Instagram' | 'LinkedIn' | 'X' | 'YouTube' | 'TikTok') | null;
        url?: string | null;
        id?: string | null;
      }[]
    | null;
  navigation?:
    | {
        label?: string | null;
        href?: string | null;
        hasDropdown?: boolean | null;
        id?: string | null;
      }[]
    | null;
  navigationCta?: {
    label?: string | null;
    href?: string | null;
  };
  footerColumns?:
    | {
        heading?: string | null;
        links?:
          | {
              label?: string | null;
              href?: string | null;
              hasDropdown?: boolean | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  footerCopyright?: string | null;
  newsletterSettings?: {
    provider?: string | null;
    heading?: string | null;
    enabled?: boolean | null;
  };
  analytics?: {
    googleAnalyticsId?: string | null;
    metaPixelId?: string | null;
  };
  defaultSeo?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
    ogTitle?: string | null;
    ogDescription?: string | null;
    ogImage?: (number | null) | Media;
    canonicalUrl?: string | null;
    noIndex?: boolean | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "homepage".
 */
export interface Homepage {
  id: number;
  heroEyebrow?: string | null;
  /**
   * Wrap the accent word(s) in **double asterisks**, e.g. 'Forge better **digital** businesses.'
   */
  heroHeading?: string | null;
  heroSubhead?: string | null;
  heroImage?: (number | null) | Media;
  heroPrimaryCta?: {
    label?: string | null;
    href?: string | null;
  };
  heroSecondaryCta?: {
    label?: string | null;
    href?: string | null;
  };
  /**
   * Leave empty to hide this section entirely.
   */
  trustBarLogos?:
    | {
        name?: string | null;
        logo?: (number | null) | Media;
        id?: string | null;
      }[]
    | null;
  /**
   * Seconds per full carousel loop. Lower = faster.
   */
  trustBarSpeed?: number | null;
  capabilitiesEyebrow?: string | null;
  capabilitiesHeading?: string | null;
  capabilitiesIntro?: string | null;
  featuredPillars?: (number | Pillar)[] | null;
  featuredWorkEyebrow?: string | null;
  featuredWorkHeading?: string | null;
  featuredProjects?: (number | Project)[] | null;
  finalCtaHeading?: string | null;
  finalCtaBody?: string | null;
  finalCtaTags?:
    | {
        tag?: string | null;
        id?: string | null;
      }[]
    | null;
  finalCtaPanelHeading?: string | null;
  finalCtaPanelBody?: string | null;
  finalCtaPanelCta?: {
    label?: string | null;
    href?: string | null;
  };
  faqEyebrow?: string | null;
  faqHeading?: string | null;
  faqIntro?: string | null;
  faqs?:
    | {
        question: string;
        answer: string;
        id?: string | null;
      }[]
    | null;
  seo?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
    ogTitle?: string | null;
    ogDescription?: string | null;
    ogImage?: (number | null) | Media;
    canonicalUrl?: string | null;
    noIndex?: boolean | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  siteName?: T;
  tagline?: T;
  logo?: T;
  contact?:
    | T
    | {
        email?: T;
        phone?: T;
        address?: T;
      };
  socialLinks?:
    | T
    | {
        platform?: T;
        url?: T;
        id?: T;
      };
  navigation?:
    | T
    | {
        label?: T;
        href?: T;
        hasDropdown?: T;
        id?: T;
      };
  navigationCta?:
    | T
    | {
        label?: T;
        href?: T;
      };
  footerColumns?:
    | T
    | {
        heading?: T;
        links?:
          | T
          | {
              label?: T;
              href?: T;
              hasDropdown?: T;
              id?: T;
            };
        id?: T;
      };
  footerCopyright?: T;
  newsletterSettings?:
    | T
    | {
        provider?: T;
        heading?: T;
        enabled?: T;
      };
  analytics?:
    | T
    | {
        googleAnalyticsId?: T;
        metaPixelId?: T;
      };
  defaultSeo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        ogTitle?: T;
        ogDescription?: T;
        ogImage?: T;
        canonicalUrl?: T;
        noIndex?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "homepage_select".
 */
export interface HomepageSelect<T extends boolean = true> {
  heroEyebrow?: T;
  heroHeading?: T;
  heroSubhead?: T;
  heroImage?: T;
  heroPrimaryCta?:
    | T
    | {
        label?: T;
        href?: T;
      };
  heroSecondaryCta?:
    | T
    | {
        label?: T;
        href?: T;
      };
  trustBarLogos?:
    | T
    | {
        name?: T;
        logo?: T;
        id?: T;
      };
  trustBarSpeed?: T;
  capabilitiesEyebrow?: T;
  capabilitiesHeading?: T;
  capabilitiesIntro?: T;
  featuredPillars?: T;
  featuredWorkEyebrow?: T;
  featuredWorkHeading?: T;
  featuredProjects?: T;
  finalCtaHeading?: T;
  finalCtaBody?: T;
  finalCtaTags?:
    | T
    | {
        tag?: T;
        id?: T;
      };
  finalCtaPanelHeading?: T;
  finalCtaPanelBody?: T;
  finalCtaPanelCta?:
    | T
    | {
        label?: T;
        href?: T;
      };
  faqEyebrow?: T;
  faqHeading?: T;
  faqIntro?: T;
  faqs?:
    | T
    | {
        question?: T;
        answer?: T;
        id?: T;
      };
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        ogTitle?: T;
        ogDescription?: T;
        ogImage?: T;
        canonicalUrl?: T;
        noIndex?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}